package rs.emulate.editor.resource.bundles.legacy.config.location

sealed class LocationProperty {
    object TypedModels : LocationProperty()
    object Name : LocationProperty()
    object Description : LocationProperty()
    object UntypedModels : LocationProperty()
    object Width : LocationProperty()
    object Length : LocationProperty()
    object Solid : LocationProperty()
    object Impenetrable : LocationProperty()
    object Interactive : LocationProperty()
    object ContourGround : LocationProperty()
    object DelayShading : LocationProperty()
    object Occlude : LocationProperty()
    object Sequence : LocationProperty()
    object DecorDisplacement : LocationProperty()
    object Brightness : LocationProperty()
    object Diffusion : LocationProperty()
    object Actions : LocationProperty()
    object Colours : LocationProperty()
    object MinimapFunction : LocationProperty()
    object Inverted : LocationProperty()
    object CastShadow : LocationProperty()
    object ScaleX : LocationProperty()
    object ScaleY : LocationProperty()
    object ScaleZ : LocationProperty()
    object Mapscene : LocationProperty()
    object Surroundings : LocationProperty()
    object TranslationX : LocationProperty()
    object TranslationY : LocationProperty()
    object TranslationZ : LocationProperty()
    object ObstructiveGround : LocationProperty()
    object Hollow : LocationProperty()
    object SupportsItems : LocationProperty()
    object Morphisms : LocationProperty()
}
